### ISSUE TITLE
Связь с 1c-syntax 

### ISSUE THREAD

**Issue by nixel2007** [andreevlex/vim-language-1c-bsl#1]
Привет! Увидел Ваш проект в пулл-реквесте к awesome-1c.
Есть два вопроса :
1) Можно ли добавить ссылку на этот проект в головной ридми 1c-syntax?  
2) Можем ли мы чем-то помочь в плане автоматизации выпуска релиза? Сейчас есть скрипты, которые автоматически собирают пакеты для атома,  vsc и st. Можно ли написать такие же скрипты для vim? Если нельзя, то будете ли Вы следить за обновлениями грамматики в головном 1c-syntax? 

Огромное спасибо за ваш продукт! Очень интересно увидеть на скриншоте готовый внешний вид :)

**Comment by ava57r** [comment]
1. Я не против, чтобы описание моего плагина для vim было в readme к 1c-syntax.
2. Я всегда за автоматизацию, но пока все этапы прошел ручками. Буду изучать вопрос автосборки файла для подсветки синтексиса. Следить на изменениями грамматики конечно буду. Первый commit содержит только основные ключевые слова, так что есть куда стремится.

3.1. Скринтшот Gvim
![vim-syntax-1c-bsl](https://cloud.githubusercontent.com/assets/20382553/19023013/51bbcf1c-88f5-11e6-89a0-406e6716c4ee.png)
3.2. Скриншот Vim (терминал)
![vim-1c-bsl-terminal](https://cloud.githubusercontent.com/assets/20382553/19032706/744de89a-896c-11e6-9acf-0ef9e859aaf9.png)

**Comment by ava57r** [comment]
Добавил основные грамматики, но без 1c-query [commit 67b60fd](https://github.com/andreevlex/vim-language-1c-bsl/commit/67b60fd49f9276a04cd23b275c1bb214dc116fc1)

**Comment by nixel2007** [comment]
Отлично! 
В 1.8.0 чуть поменяются определители директив и инструкций, я отдельно напишу потом.

**Comment by ava57r** [comment]
Добавил все грамматики из 1с-syntax [https://github.com/andreevlex/vim-language-1c-bsl/commit/f2c75c51731eba5151724d2dfc58487881a8c203](https://github.com/andreevlex/vim-language-1c-bsl/commit/f2c75c51731eba5151724d2dfc58487881a8c203)
Для 1c-query есть подсветка в отдельном файле и внутри bsl

**Comment by ava57r** [comment]
Мне кажется в одном из выражений есть недочет
файл `1c-query.YAML-tmLanguage`
грамматика `keyword.control.sdbl`
исходное -`(Внешнее|Outer\s+)?`, так "Outer" будет подсвечен только с пробелом
исправленное - `(Внешнее|Outer)?\s+`

**Comment by nixel2007** [comment]
Тогда будет требоваться два пробела, скорее \s+ надо продублировать у русской лексемы. Но в целом да - это ошибка. Можете зарегистрировать ишуз и сделать пулл-реквест?

**Comment by nixel2007** [comment]
А в Вашей реализации текст запроса подсвечивается внутри строки в bsl файле или только отдельно?

**Comment by ava57r** [comment]
> А в Вашей реализации текст запроса подсвечивается внутри строки в bsl файле или только отдельно?

Текст запроса подсвечивается внутри строки bsl файла и в отдельном файле

**Comment by ava57r** [comment]
> Тогда будет требоваться два пробела, скорее \s+ надо продублировать у русской лексемы. Но в целом да - это ошибка. Можете зарегистрировать ишуз и сделать пулл-реквест? 

Да согласен если смотреть на все выражение целиком, то будет требоваться 2 пробела.

**Comment by ava57r** [comment]
> Тогда будет требоваться два пробела, скорее \s+ надо продублировать у русской лексемы. Но в целом да - это ошибка. Можете зарегистрировать ишуз и сделать пулл-реквест?

отправил пулл-реквест

**Comment by ava57r** [comment]
Грамматики портированы в VIM. 
Дополнительные возможности буду делать другими задачами.
