### ISSUE TITLE
Список процедур\функций модуля

### ISSUE THREAD

**Issue by anatolean** [andreevlex/vim-language-1c-bsl#10]
Добрый день.
Уточните, пожалуйста, есть ли возможность просмотра списка процедур модуля и перехода к нужной?
Спасибо большое за плагин!

**Comment by ava57r** [comment]
Добрый.
Такая функция есть.
За это отвечает плагин tagbar
Вот строка из `.vimrc`, которая указывает пакетному менеджеру Vundle.vim задействовать tagbar.
```vim
Plugin 'majutsushi/tagbar'          	" Class/module browser
```
файл `.ctags` - отвечает за поиск тех самых функций и процедур в файле. Нужен для правильной работы с файлом программы Exuberant ctags.
Вот tagbar и ctags работают совместно.
У tagbar есть настройки различные
```vim
 " TagBar настройки
map <F4> :TagbarToggle<CR>
let g:tagbar_autofocus = 0 " автофокус на Tagbar при открытии
```
Настройки выше позволят открывать окно tagbar  по нажатию F4.

**Comment by ava57r** [comment]
1. Переход к нужной строке можно осуществить, например 
- переключится на окно с tagbar `Ctrl-W`
- выбрать строку с нужной функцией или процедурой и нажать `Enter`
Так вы окажитесь на нужной строке.
2. Выполнить команду в `:!ctags file.bsl`,чтобы создать файл меток для вашего файла. 
- в каталоге с файлом будет создан файл tags.
- выполнить команду в редакторе `:tag имя тэга`
Так вы тоже попадёте на необходимую строку. При вводе тэга поддерживается автодополнение по нажатию клавиши TAB.

**Comment by anatolean** [comment]
Большое спасибо за столь подробный ответ. 
Очень помогли. 
Хорошего дня.

**Comment by ava57r** [comment]
Отразил данную задачу в Wiki
[Просмотр списка процедур и функций текущего модуля](https://github.com/andreevlex/vim-language-1c-bsl/wiki/%D0%9F%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D0%B4%D1%83%D1%80-%D0%B8-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9-%D1%82%D0%B5%D0%BA%D1%83%D1%89%D0%B5%D0%B3%D0%BE-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F)
и
[Переход к определению процедуры или функции](https://github.com/andreevlex/vim-language-1c-bsl/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4-%D0%BA-%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D0%B4%D1%83%D1%80%D1%8B-%D0%B8%D0%BB%D0%B8-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8)
