### ISSUE TITLE
Сделать поддержку плагина tagbar

### ISSUE THREAD

**Issue by ava57r** [andreevlex/vim-language-1c-bsl#3]
[Vim plugin that displays tags in a window, ordered by scope http://majutsushi.github.com/tagbar/](http://majutsushi.github.com/tagbar/)

**Comment by ava57r** [comment]
@dmpas подскажите как работает [https://github.com/dmpas/oscript-tagbar](https://github.com/dmpas/oscript-tagbar)?

Тут [https://github.com/majutsushi/tagbar/wiki](https://github.com/majutsushi/tagbar/wiki) написано, что необходимо еще создавать ~/.ctags для поддержки новых языков.

**Comment by dmpas** [comment]
@andreevlex tagbar работает через ctags, то есть сам ничего не парсит.
а вот с CTAGS боль. Вот пример моей настройки:

```
--langdef=onescript
--langmap=onescript:.os.1src.bsl.e8s
--regex-onescript=/^[ \t]*Процедура[ \t]+([^\(]*)/\1/f,function,functions/i
--regex-onescript=/^[ \t]*Функция[ \t]+([^\(]*)/\1/f,function,functions/i
```

но с каким-то из обновлений даже не помню чего, это перестало работать. Проблемы те же - невосприятие кириллицы, потому я плюнул пока на это дело и теперь не знаю, либо допиливать ctags, либо использовать парсер ОдноСкрипта.

**Comment by ava57r** [comment]
Вот и я когда пошел по пути написания РВ для ctags с этим столкнулся.
Для ctags буду копать в сторону написания парсера.

**Comment by dmpas** [comment]
@andreevlex это тогда придётся свою сборку ctags хранить и распространять.

Вот я в былые времена мучался: https://github.com/dmpas/geane8/blob/master/tagmanager/ctags/e8script.c

**Comment by ava57r** [comment]
Делать сборку всего ctags это путь в некуда (Тяжело поддерживать актуальность для других языков). Надо толково написать и сделать pull request в основную ветку [https://github.com/universal-ctags/ctags](https://github.com/universal-ctags/ctags).

А вот нашел. Можно написать совместимый парсер на другом языке [http://docs.ctags.io/en/latest/xcmd.html#extending-ctags-with-xcmd](http://docs.ctags.io/en/latest/xcmd.html#extending-ctags-with-xcmd)
Думаю кандидат - это python, он Unicode поддерживает.

**Comment by ava57r** [comment]
Добавлена поддержка плагина Tagbar [428a4c6](https://github.com/andreevlex/vim-language-1c-bsl/tree/428a4c68fba27f7e6cf5a89e60701824b4854b01)
Как не удивительно все работает на регулярках.
